///////////////////////////////////////////////////////////
//  Chenille.cs
//  Implementation of the Class Chenille
//  Generated by Enterprise Architect
//  Created on:      12-déc.-2022 09:57:07
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




public class Chenille : StadesDEvolution {

	public Chenille(){

	}

	~Chenille(){

	}

	public override void Dispose(){

	}

	public void Metamorphose(){

	}

	public string Manger(){

		return "";
	}

	public override string SeDeplacer(){

		return "";
	}

}//end Chenille