///////////////////////////////////////////////////////////
//  Papillon.cs
//  Implementation of the Class Papillon
//  Generated by Enterprise Architect
//  Created on:      12-déc.-2022 09:57:07
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




public class Papillon : StadesDEvolution {

	public Papillon(){

	}

	~Papillon(){

	}

	public override void Dispose(){

	}

	public void Metamorphose(){

	}

	public string SeDeplacer(){

		return "";
	}

	public string Voler(){

		return "";
	}

}//end Papillon