///////////////////////////////////////////////////////////
//  Chrysalide.cs
//  Implementation of the Class Chrysalide
//  Generated by Enterprise Architect
//  Created on:      12-déc.-2022 09:57:07
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




public class Chrysalide : StadesDEvolution {

	public Chrysalide(){

	}

	~Chrysalide(){

	}

	public override void Dispose(){

	}

	public void Metamorphose(){

	}

	public override string SeDeplacer(){

		return "";
	}

	public void SeDevelopper(){

	}

}//end Chrysalide