///////////////////////////////////////////////////////////
//  Lepidoptere.cs
//  Implementation of the Class Lepidoptere
//  Generated by Enterprise Architect
//  Created on:      12-déc.-2022 09:57:07
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




public class Lepidoptere {

	private StadesDEvolution m_StadesDEvolution;

	public Lepidoptere(){

	}

	~Lepidoptere(){

	}

	public virtual void Dispose(){

	}

	public void EtatActuel(){

	}

}//end Lepidoptere