///////////////////////////////////////////////////////////
//  Oeuf.cs
//  Implementation of the Class Oeuf
//  Generated by Enterprise Architect
//  Created on:      12-déc.-2022 09:57:07
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




public class Oeuf : StadesDEvolution {

	public Oeuf(){

	}

	~Oeuf(){

	}

	public override void Dispose(){

	}

	public void Metamorphose(){

	}

	public void Remuer(){

	}

	public override string SeDeplacer(){

		return "";
	}

	public string Eclore(){

		return "";
	}

}//end Oeuf