///////////////////////////////////////////////////////////
//  StadesDEvolution.cs
//  Implementation of the Class StadesDEvolution
//  Generated by Enterprise Architect
//  Created on:      12-déc.-2022 09:57:07
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




public abstract class StadesDEvolution {

	public StadesDEvolution(){

	}

	~StadesDEvolution(){

	}

	public virtual void Dispose(){

	}

	public abstract void Metamorphose();

	public abstract string SeDeplacer();

}//end StadesDEvolution